nodes: 8
tasks_per_node: 8
tag: real_fake_16_2x3
eval_name: video_analysis
resume_checkpoint: false
data:
  json_config_path: /blob/kyoungjun/InternVid-10M-flt-zipindex.json
  # since, the real video are not in one path, how to handle this efficiently? 
  real_video_paths:
    - /blob/kyoungjun/internvid_flt_1_reformatted
    - /blob/kyoungjun/internvid_flt_2_reformatted
    - /blob/kyoungjun/internvid_flt_3_reformatted
    - /blob/kyoungjun/internvid_flt_4_reformatted
    - /blob/kyoungjun/internvid_flt_5_reformatted
    - /blob/kyoungjun/internvid_flt_6_reformatted
    - /blob/kyoungjun/internvid_flt_7_reformatted
    - /blob/kyoungjun/internvid_flt_8_reformatted
    - /blob/kyoungjun/internvid_flt_9_reformatted
    - /blob/kyoungjun/internvid_flt_10_reformatted
  fake_video_path:
    - /blob/kyoungjun/gen_internvid_flt
  dataset_type: InternVidDataset
  num_classes: 2
  frames_per_clip: 16
  num_segments: 2
  num_views_per_segment: 3
  frame_step: 4
optimization:
  attend_across_segments: true
  num_epochs: 20
  resolution: 384
  batch_size: 4
  weight_decay: 0.01
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: true
pretrain:
  model_name: vit_huge
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_silu: false
  tight_silu: false
  use_sdpa: true
  patch_size: 16
  folder: /blob/muaz/jepa
  checkpoint: vith16-384.pth.tar # name of pretrained model file inside folder
  write_tag: jepa
